import Hash "mo:base/Hash";
import Int "mo:base/Int";
import List "mo:base/List";
import Order "mo:base/Order";
import Stack "mo:base/Stack";

import Text "mo:base/Text";
import HashMap "mo:base/HashMap";
import Iter "mo:base/Iter";
import Array "mo:base/Array";

actor {
  private stable var guideEntriesStable : [(Text, Text)] = [];
  private var guideContent = HashMap.HashMap<Text, Text>(10, Text.equal, Text.hash);

  private func initializeContent() {
    let defaultContent = [
      ("talents", "Essential Talents for Brewmaster Monk:\n\nClass Tree:\n- Improved Vivify\n- Chi Wave\n- Tiger's Lust\n- Ring of Peace\n- Summon Black Ox Statue\n- Improved Celestial Brew\n- Bob and Weave\n- Improved Purifying Brew\n- Celestial Flames\n- Blackout Combo\n- High Tolerance\n- Exploding Keg\n\nMonk Tree Highlights:\n- Generous Pour\n- Grace of the Crane\n- Fast Feet\n- Improved Roll\n- Close to Heart\n- Touch of Death\n- Detox\n- Healing Elixir"),
      
      ("stats", "Stat Priority Guide:\n\nPrimary Stats:\n1. Stamina - Your most important defensive stat\n2. Armor - Base physical damage reduction\n3. Agility - Increases attack power and armor\n\nSecondary Stats (in order):\n1. Versatility\n- Increases damage done\n- Reduces damage taken\n- Best overall defensive stat\n\n2. Mastery\n- Increases Stagger effectiveness\n- Improves Elusive Brawler dodge chance\n\n3. Critical Strike\n- Improves healing received\n- Increases damage output\n- Affects Celestial Fortune healing\n\n4. Haste\n- Reduces global cooldown\n- Faster energy regeneration\n- More frequent Keg Smash casts"),
      
      ("single_target", "Single Target Rotation Guide:\n\nCore Abilities Priority:\n1. Keg Smash on cooldown\n- Primary damage and threat ability\n- Reduces brew cooldowns\n- Applies Mystic Touch\n\n2. Blackout Kick\n- Use with Blackout Combo talent\n- Generates Shuffle duration\n- Provides damage reduction\n\n3. Breath of Fire\n- Maintains damage reduction debuff\n- Good damage output\n- 15-second cooldown\n\n4. Tiger Palm\n- Energy filler\n- Generates Shuffle duration\n- Low priority\n\nDefensive Priority:\n1. Maintain Shuffle (100% uptime)\n- Generated by Blackout Kick and Tiger Palm\n- Essential for damage reduction\n\n2. Purifying Brew Usage\n- Use at Yellow Stagger (60%+ health)\n- Use at Red Stagger (immediate)\n- Don't overcap charges\n\n3. Celestial Brew\n- Use between damage spikes\n- Stack Purified Chi before use\n- Don't save for emergencies\n\nOpener Sequence:\n1. Weapons of Order\n2. Keg Smash\n3. Breath of Fire\n4. Blackout Kick\n5. Establish rotation\n\nAdvanced Tips:\n- Pool energy for Keg Smash\n- Track Shuffle duration closely\n- Use Celestial Brew proactively\n- Maintain Breath of Fire debuff"),
      
      ("aoe", "AOE Rotation Guide:\n\nPriority List (3+ Targets):\n1. Keg Smash\n- Primary threat generator\n- Hits up to 5 targets\n- Reduces brew cooldowns\n\n2. Rushing Jade Wind\n- Maintain 100% uptime\n- Good consistent AOE damage\n- Energy efficient\n\n3. Spinning Crane Kick\n- Use with excess energy\n- Good for large packs\n- Generates significant threat\n\n4. Breath of Fire\n- Maintains debuff on all targets\n- Significant damage reduction\n- Important for survivability\n\nDefensive Considerations:\n1. Shuffle Uptime\n- Even more critical in AOE\n- Use Spinning Crane Kick if needed\n\n2. Purifying Brew\n- More frequent use needed\n- Watch Stagger levels closely\n\n3. Celestial Brew\n- Use for large incoming damage\n- Coordinate with other defensives\n\nCooldown Usage:\n1. Bonedust Brew\n- Use on cooldown\n- Amplifies all damage\n- Helps with threat\n\n2. Weapons of Order\n- Great for burst AOE\n- Use on larger pulls\n\n3. Exploding Keg\n- Both offensive and defensive\n- Use for dangerous packs\n\nPositioning Tips:\n1. Group Control\n- Use Ring of Peace\n- Position for Breath of Fire\n- Maintain line of sight\n\n2. Black Ox Statue\n- Place centrally\n- Use for pulling\n- Helps with scattered mobs"),
      
      ("cooldowns", "Defensive Cooldowns and Mitigation:\n\nCore Defensive Abilities:\n1. Purifying Brew\n- 2 charges, 20-second recharge\n- Removes 50% of Stagger damage\n- Use at Yellow/Red Stagger\n- Don't save both charges\n\n2. Celestial Brew\n- 1-minute cooldown\n- Scales with Purified Chi\n- Use proactively\n- Don't save for emergencies\n\n3. Fortifying Brew\n- 7-minute cooldown\n- 20% damage reduction\n- 20% health increase\n- Use for dangerous mechanics\n\nSituational Defensives:\n1. Zen Meditation\n- 5-minute cooldown\n- 60% damage reduction\n- Breaks on movement/attacks\n- Good for magic damage\n\n2. Dampen Harm\n- 2-minute cooldown\n- 45% reduction to big hits\n- Good for predictable damage\n\n3. Healing Elixir\n- 2 charges, 30-second recharge\n- 15% max health healing\n- Use as needed\n\nStagger Management:\n1. When to Purify:\n- Yellow: Above 60% health\n- Red: Immediate priority\n- During high damage\n\n2. Celestial Brew Usage:\n- Stack Purified Chi first\n- Use between damage spikes\n- Coordinate with other defensives\n\nEmergency Buttons:\n1. Health Stone\n2. Healing Potion\n3. Healthstone"),
      
      ("utilities", "Utility Abilities Guide:\n\nMovement Abilities:\n1. Roll/Chi Torpedo\n- 2 charges baseline\n- Quick positioning\n- Dodge mechanics\n- 20-second recharge\n\n2. Transcendence\n- Place in safe spot\n- 45-second cooldown\n- Great for mechanics\n- Can cheese some fights\n\nCrowd Control:\n1. Ring of Peace\n- 45-second cooldown\n- Displacement tool\n- Interrupt casts\n- Position control\n\n2. Leg Sweep\n- 60-second cooldown\n- AOE stun (5 yards)\n- 5-second duration\n- Interrupt dangerous casts\n\nTank Utilities:\n1. Provoke\n- 30-yard range\n- 8-second cooldown\n- Tank swaps\n- Snap threat generation\n\n2. Spear Hand Strike\n- 15-second cooldown\n- Interrupt\n- Critical for casters\n- Short range\n\n3. Black Ox Statue\n- Area threat generation\n- Positioning tool\n- Pull distant mobs\n\nRaid Utilities:\n1. Mystic Touch\n- 5% physical damage\n- Raid-wide benefit\n- Always maintain\n\n2. Detox\n- Removes poisons/diseases\n- 8-second cooldown\n- Utility dispel\n\nMiscellaneous:\n1. Vivify\n- Emergency healing\n- Use while kiting\n- Costs significant energy\n\n2. Expel Harm\n- Small self-heal\n- Generates Chi\n- Use on cooldown")
    ];

    for ((k, v) in defaultContent.vals()) {
      guideContent.put(k, v);
    };
  };

  initializeContent();

  system func preupgrade() {
    guideEntriesStable := Iter.toArray(guideContent.entries());
  };

  system func postupgrade() {
    guideContent := HashMap.fromIter<Text, Text>(guideEntriesStable.vals(), 10, Text.equal, Text.hash);
    if (guideContent.size() == 0) {
      initializeContent();
    };
  };

  public query func getSection(section : Text) : async ?Text {
    guideContent.get(section)
  };

  public query func getAllSections() : async [(Text, Text)] {
    Iter.toArray(guideContent.entries())
  };

  public func updateSection(section : Text, content : Text) : async () {
    guideContent.put(section, content);
  };
}
